### PR TITLE
Port Silex to Scala 3

### PR DESCRIPTION
**Pull request by brunnerant**
This PR ports the code base to Scala 3. It was pretty straightforward, but here are a few notes:
- Implicit classes used to add decorator methods were translated to extension methods. In Scala 3.0, implicits are still supported, but will gradually be removed from the language in future versions.
- `scala.Seq` aliases to `scala.collection.Seq` in Scala 2.12, while it aliases to `scala.collection.immutable.Seq` in later versions. This causes some problems with conversions from `ArrayBuffer` to `Seq`, and some types had to be changed.
- `FlatSpec` was renamed to `AnyFlatSpec` starting from scalatest 3.1.0.

For now, there seem to be some problems with the package documentation and `scaladoc`. I tried to dig further but couldn't find a solution to the problem. It seems to be [an open issue](https://github.com/lampepfl/dotty/issues/11284), though...

### CODE REVIEW

**Comment by LPTK** [comment]
Thanks for the PR. However, it seems cross compilation is broken. I tried `++ 2.12.13` and `publishLocal`, and got errors about the `extension` keyword in `Lexers.scala`. To allow cross-compilation, should probably be either kept as an implicit class, or the code should replicated into version-specific folders.

**Comment by LPTK** [comment]
By the way, are you also looking into porting https://github.com/epfl-lara/scallion at the moment?

**Comment by brunnerant** [comment]
Sorry, I had notification issues with GitHub, I didn't realized you replied :/... Indeed, we could maybe keep the old syntax as well if we want to be able to cross compile. However, in future versions of Scala 3, the old implicits will be removed, I believe. But we can probably handle that later on.

**Comment by redelmann** [comment]
I'm not against breaking backwards compatibility regarding implicits.

Also, do we have any updates regarding the documentation bug?

**Comment by brunnerant** [comment]
Ok. The documentation bug is still present, I tried a few things but couldn't work around it. If you want to see what the problem is, you can open the file `docs/api/silex.html`, and you can see that the package documentation is missing...
This only occurs with the Scala 3 version of the docs, so if it might have something to do with the fact that package objects will be eventually removed in Scala 3.

**Comment by pikinier20** [comment]
Hey, I've seen a reference to the issue in Scaladoc. I would like to add here that we added legacy support for documentation to the package written as documentation to the package object. It's been working starting from 3.1.0.

**Pull request merged**
